### ISSUE TITLE
nginx  issue

### ISSUE THREAD

**Issue by itranga** [jamg44/NodeTyped#6]
I try to config api with nginx in aws . I got the following issue.

Nginx config

location /api/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_set_header X-NginX-Proxy true;
                proxy_redirect off;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                #try_files $uri$args $uri$args/ /index.html;

                proxy_pass http://127.0.0.1:3000;

        }

I stated app using PM2 . 

Issue 

http://34.208.10.117/api/products

Not Found

404

Error
    at app.use (/usr/share/nginx/html/orderanythingapi/src/app.ts:59:13)
    at Layer.handle [as handle_request] (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:312:13)
    at /usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:271:10)
    at /usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:618:15
    at next (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:256:14)
    at Function.handle (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:176:3)
    at router (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:46:12)
    at Layer.handle [as handle_request] (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:312:13)
    at /usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:330:12)
    at next (/usr/share/nginx/html/orderanythingapi/node_modules/express/lib/router/index.js:271:10)
    at SendStream.error (/usr/share/nginx/html/orderanythingapi/node_modules/serve-static/index.js:121:7)

**Comment by jamg44** [comment]
Hi @itranga 

It could be Express is evaluating the full path (/api/products) and not matching any of your middlewares (/products, /apiv1/products, etc)

Try to change the message on your 404 middleware to show the originalUrl that is being evaluated, i.e:

```
// catch not handled and return 404
app.use((req, res, next) => next({
    message: 'Not Found - ' + req.originalUrl,  // <------- here
    status: 404,
    stack: (new Error()).stack
}));
```

That will give you clues about what is happening.

Javier

**Comment by itranga** [comment]
Thanks for your help . I changed middleware . i got the same issue  . I forward http://127.0.0.1:3000 to api in nginx config .

**Comment by itranga** [comment]
I fixed it . I have changed aws configuration . Thanks for your help .
