### ISSUE TITLE
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node"

### ISSUE THREAD

**Issue by sandgupta23** [jamg44/NodeTyped#8]
I am getting this error after npm install:

$ npm install
```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher                                                                                                                 to avoid a RegExp DoS issue

> node-sass@3.13.1 install C:\Users\HP\Desktop\nodebook\projectname\node_modules                                                                                                                \node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.1                                                                                                                3.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win                                                                                                                32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe C:\Users\HP\Desktop\nodebook\projectn                                                                                                                ame\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --lib                                                                                                                sass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\HP\\Desktop\\nodebook\\projectname\\node_modules\\nod                                                                                                                e-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\HP\Desktop\nodebook\pr                                                                                                                ojectname\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\HP\Desktop\nodebook\projectname\node_                                                                                                                modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\HP\Desktop\nodebook\projectname\node_                                                                                                                modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\HP\Desktop\nodebook\pr                                                                                                                ojectname\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\HP\Desktop\nodebook\projectname\node_                                                                                                                modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\HP\Desktop\nodebook\projectname\node_                                                                                                                modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\HP\Desktop\nodebook\projectname\node_mod                                                                                                                ules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundE                                                                                                                rror (C:\\Users\\HP\\Desktop\\nodebook\\projectname\\node_modules\\which\\which.                                                                                                                js:13:12)\n    at F (C:\\Users\\HP\\Desktop\\nodebook\\projectname\\node_modules                                                                                                                \\which\\which.js:68:19)\n    at E (C:\\Users\\HP\\Desktop\\nodebook\\projectnam                                                                                                                e\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\HP\\Desktop\\nodebook                                                                                                                \\projectname\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\HP\\Deskto                                                                                                                p\\nodebook\\projectname\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\                                                                                                                HP\\Desktop\\nodebook\\projectname\\node_modules\\isexe\\windows.js:36:5\n    at                                                                                                                 FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\HP\AppData\Local\Programs\Python\Pyth                                                                                                                on36-32\python.EXE
gyp verb check python version `C:\Users\HP\AppData\Local\Programs\Python\Python3                                                                                                                6-32\python.EXE -c "import platform; print(platform.python_version());"` returne                                                                                                                d: "3.6.4\r\n"
gyp verb could not find "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\p                                                                                                                ython.EXE". checking python launcher
gyp verb could not find "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\p                                                                                                                ython.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\HP\AppData\Local\Pr                                                                                                                ograms\Python\Python36-32\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\HP\Desktop\nodebook\pr                                                                                                                ojectname\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\HP\Desktop\nodebook\pro                                                                                                                jectname\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\HP\Desktop\nodebook\projectname\node_modules\grac                                                                                                                eful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HP\\Desktop\\                                                                                                                nodebook\\projectname\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--ve                                                                                                                rbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_libr                                                                                                                ary="
gyp ERR! cwd C:\Users\HP\Desktop\nodebook\projectname\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN bootstrap@4.0.0 requires a peer of popper.js@^1.12.9 but none is instal                                                                                                                led. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fse                                                                                                                vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                                )

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HP\AppData\Roaming\npm-cache\_logs\2018-03-14T16_26_09_838                                                                                                                Z-debug.log

```

**Comment by jamg44** [comment]
Updated node-sass to avoid this

**Comment by MrDrSushi** [comment]
where do you update?
